version: '3'
services:
    front:
        image: front-image
        depends_on:
            - "back"
        ports:
            - "80:80"
        environment:
            - ENV=dev

    back:
        image: springio/gs-spring-boot
        ports:
            - "8080:8080"
        environment:
            - ENV=dev
